spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        nodeValue:
          dialect: org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb
    defer-datasource-initialization: true
    datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
      username: sa
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
  session:
    initialize-schema: always
    table-name: SPRING_SESSION
#    store-type: jdbc
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql

server:
  servlet:
    encoding:
      force-response: true

