spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
server:
  servlet:
    encoding:
      force-response: true