spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        nodeValue:
          dialect: org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb
    defer-datasource-initialization: true
    datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
      username: sa
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
  session:
    store-type: jdbc

server:
  servlet:
    encoding:
      force-response: true
  port: 8090

