spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
  session:
    store-type: jdbc
server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true
