spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        nodeValue:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          storage_engine: innodb
    defer-datasource-initialization: true
    datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
      username: sa
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  pid:
    file: /home/ec2-user/app/step2/aws_spring.pid
server:
  servlet:
    encoding:
      force-response: true

